services:
  reverse-proxy:
    image: traefik:v3.1.5
    container_name: traefik_proxy

    command:
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.directory=/etc/traefik"
      - "--providers.file.watch=true"
      - "--api.insecure=true"
      - "--log.level=DEBUG"

    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro

    networks:
      - traefik-net
    restart: unless-stopped

  backend:
    image: nginx:latest
    container_name: backend
    networks:
      - traefik-net
    volumes:
      - ./backend/html:/usr/share/nginx/html:ro
    # optional: expose port for debugging
    ports:
      - "8000:80"

  ja4-service:
    build: ./ja4-service
    container_name: ja4-service
    environment:
      - PYTHONUNBUFFERED=1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ja4.rule=Host(`nkb.local`)"
      - "traefik.http.routers.ja4.entrypoints=web"
      - "traefik.http.services.ja4.loadbalancer.server.port=5001"
    networks:
      - traefik-net

  decision-engine:
    build: ./decision-engine
    container_name: decision-engine
    environment:
      - PYTHONUNBUFFERED=1
      - BLOCKLIST=t13i9012h2_8da3,t13i7712h2_abcd
    networks:
      - traefik-net

  test-client:
    image: alpine:latest
    container_name: test-client
    command: ["sleep", "infinity"]
    networks:
      - traefik-net

networks:
  traefik-net:
    driver: bridge
